

# Disable the blank line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[python]
disabled = true

[gcloud]
disabled = true

[username]
disabled = true
